# 統計純作多

In [7]:
import pandas as pd
import os
import matplotlib.pyplot as plt
from matplotlib.font_manager import FontProperties

font_path = '/Library/Fonts/Arial Unicode.ttf'  # 這是 macOS 上的一個中文字體
font_prop = FontProperties(fname=font_path)
plt.rcParams['font.sans-serif'] = ['Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False  

def get_price_his(stock_id, country):
    path_price_his = f"{os.path.abspath(os.getcwd())}/history_data/{country}/stock_price/{stock_id}tech.csv"
    df_price_his = pd.read_csv(path_price_his, encoding="utf-8")
    df_price_his["Date"] = pd.to_datetime(df_price_his["Date"], format="%Y%m%d")
    # 讓時間在 2023-01-01 之後
    df_price_his = df_price_his[df_price_his["Date"] >= "2022-01-01"]
    df_price_his = df_price_his[df_price_his["Date"] <= "2025-01-01"]
    
    return df_price_his
    
stocks = [
    ["twii", "台灣指數期貨", "tw"],
    # ["2330", "台積電", "tw"],
    # ["2454", "聯發科", "tw"],
    # ["2317", "鴻海", "tw"],
    # ["2308", "台達電", "tw"],
    # ["2382", "廣達", "tw"],
    # ["2412", "中華電", "tw"],
    # ["2881", "富邦金", "tw"],
    # ["2882", "國泰金", "tw"],
    # ["2891", "中信金", "tw"],
    # ["6505", "台塑化", "tw"],
    
    # ["3231", "緯創", "tw"],
    # ["2207", "和泰車", "tw"],
    # ["3661", "世芯", "tw"],
    # ["2603", "長榮", "tw"],
    # ["2408", "南亞科", "tw"],
    
    ["spx", "S&P 500", "us"],
    # ["AAPL", "Apple Inc.", "us"],
    # ["MSFT", "Microsoft", "us"],
    # ["NVDA", "Nvidia", "us"],
    # ["AMZN", "Amazon inc.", "us"],
    # ["META", "Meta Platforms", "us"],
    # ["GOOGL", "Google", "us"],
    # ["TSLA", "Tesla", "us"],
    # ["AVGO", "Broadcom", "us"],
    # ["BRK", "Berkshire Hathaway", "us"],
    # ["JPM", "JPMorgan Chase", "us"],
    
    # ["BA", "Boeing", "us"],
    # ["MRNA", "Moderna", "us"],
    # ["WMT", "Walmart", "us"],
    # ["UNH", "UnitedHealth Group", "us"],
    # ["DIS", "Disney", "us"],
]

rtns = []
tp = 0
fp = 0
tn = 0
fn = 0
for stock in stocks:
    stock_id = stock[0]
    stock_name = stock[1]
    country = stock[2]

    price_his = get_price_his(stock_id, country)
    display(price_his.head())
    
    for idx, price in price_his.iterrows():
        # print(price)
        rtn = (price["Close"] - price["Open"]) / price["Open"]
        if rtn > 0:
            rtns.append(rtn)
            tp += 1
        else:
            rtns.append(rtn)
            fp += 1
    
    print(f"{stock_name} 平均報酬: {sum(rtns) / len(rtns)}")
    print("Accuracy: ", tp / (tp + fp + tn + fn))
    print("Precision: ", tp / (tp + fp))

,Date,Open,High,Low,Close,MA5,MA10,MA20,EMA5,EMA12,EMA26,EMA60,DIF,MACD,RSI,Volatility,K,D
5724,2022-01-03,18260.23,18379.69,18238.47,18270.51,18196.676,18017.689,17893.011,18181.837579,18034.935483,17860.669747,17860.669747,174.265736,137.563236,71.216071,0.071986,87.773435,84.598730
5725,2022-01-04,18395.14,18526.35,18395.14,18526.35,18292.158,18103.413,17934.918,18296.675053,18110.537716,17909.979395,17909.979395,200.558321,150.162253,86.414418,0.066136,91.848956,87.015472
5726,2022-01-05,18598.13,18619.61,18446.52,18499.96,18352.788,18174.482,17970.070,18364.436702,18170.448837,17953.681662,17953.681662,216.767175,163.483238,83.906886,0.071111,89.344478,87.791807
5727,2022-01-06,18395.72,18427.15,18253.82,18367.92,18376.716,18228.591,17996.845,18365.597801,18200.829016,17984.365983,17984.365983,216.463032,174.079196,73.382977,0.088609,80.299978,85.294531
5728,2022-01-07,18388.16,18444.12,18134.41,18169.76,18366.900,18250.901,18009.627,18300.318534,18196.049167,17998.098874,17998.098874,197.950293,178.853416,62.610243,0.107489,63.589719,78.059594

台灣指數期貨 平均報酬: -4.6019979476752046e-05
Accuracy:  0.546079779917469
Precision:  0.546079779917469

,Date,Volume,Open,High,Low,Close,MA5,MA10,MA20,EMA5,EMA12,EMA26,EMA60,EMA120,DIF,MACD,RSI,K,D
489,2022-01-03,NaN,4778.14,4796.64,4758.17,4796.56,4784.176,4735.167,4700.6495,4775.551660,4739.742331,4697.947973,4629.284701,4518.992682,41.794358,30.653647,61.717329,89.599992,85.602364
490,2022-01-04,NaN,4804.51,4818.62,4774.27,4793.54,4785.614,4757.719,4710.7430,4781.547773,4748.018896,4705.028864,4634.670120,4523.530654,42.990032,33.120924,65.553366,88.236804,86.480510
491,2022-01-05,NaN,4787.99,4797.70,4699.44,4700.58,4767.118,4762.854,4711.4345,4754.558515,4740.720604,4704.699319,4636.831100,4526.457089,36.021285,33.700996,49.125125,59.143382,77.368134
492,2022-01-06,NaN,4693.39,4725.01,4671.26,4696.05,4750.582,4762.803,4711.1765,4735.055677,4733.848203,4704.058628,4638.772703,4529.260278,29.789575,32.918712,52.776088,45.036503,66.590924
493,2022-01-07,NaN,4697.66,4707.95,4662.74,4677.03,4732.752,4757.927,4711.6555,4715.713785,4725.106941,4702.056508,4640.027041,4531.702753,23.050434,30.945056,56.074807,33.080105,55.420651

S&P 500 平均報酬: 4.485032880368416e-05
Accuracy:  0.5351351351351351
Precision:  0.5351351351351351