In [23]:
import os
import textwrap
import math
import json
import pandas as pd
import numpy as np
from collections import Counter
from datetime import datetime
from dateutil.relativedelta import relativedelta
from IPython.display import display
from IPython.display import Markdown

from langchain_openai import ChatOpenAI

import api


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

llm = ChatOpenAI(
  openai_api_key = os.getenv('OPENAI_API_KEY'),
  model='gpt-4o-mini',
  temperature=1,
)

# 買進賣出需要的手續費
fee = {
  'tax_stock' : 0.003,          # 買進與賣出各0.003
  'tax_future' : 0.00002 * 2,   # 買進與賣出各0.00002
  'fee_stock' : 0.001425 * 2,   # 券商手續費公道價，買進與賣出各0.001425
  'fee_future' : 0.00002 * 2,   # 個家不大相同，以交易稅計算
  'sliding_price' : 0.00001,    # 滑價
}

env = {
    "stock_id" : "TSLA",
    "country" : "us",
    "start_date" : "20231001",
    "end_date" : "20240930",
    "path_out" : "out_stock/GA_sot_4omini/",
}

# 載入 factors

In [24]:
factors = {}
path_factors = f"{env['path_out']}{env['stock_id']}/factors.json"
print(path_factors)
with open(path_factors, "r") as f:
  factors = json.load(f)

# Access by index using list of keys
key_list = list(factors.keys())
value_list = list(factors.values())
print(key_list)
print(len(key_list))
print(len(value_list))

out_stock/GA_sot_4omini/TSLA/factors.json
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']
30
30

# 延伸factors

In [25]:
from api import factor_expanding

# 讀取舊資料
old_data = {}
path_expand = f"{env['path_out']}{env['stock_id']}/expand.json"
os.makedirs(os.path.dirname(path_expand), exist_ok=True)
if os.path.exists(path_expand):
    with open(path_expand, 'r') as f:
        old_data = json.load(f)

data = factor_expanding(llm, env, key_list, value_list, old_data)

# 儲存資料
with open(path_expand, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

running... factor_expanding
Already processed for date 20240930, skip this date
Already processed for date 20240927, skip this date
Already processed for date 20240926, skip this date
Already processed for date 20240925, skip this date
Already processed for date 20240924, skip this date
Already processed for date 20240923, skip this date
Already processed for date 20240920, skip this date
Already processed for date 20240919, skip this date
Already processed for date 20240918, skip this date
Already processed for date 20240917, skip this date
Already processed for date 20240916, skip this date
Already processed for date 20240913, skip this date
Already processed for date 20240912, skip this date
Already processed for date 20240911, skip this date
Already processed for date 20240910, skip this date
Already processed for date 20240909, skip this date
Already processed for date 20240906, skip this date
Already processed for date 20240905, skip this date
Already processed for date 20240904, skip this date
Already processed for date 20240903, skip this date
Already processed for date 20240830, skip this date
Already processed for date 20240829, skip this date
Already processed for date 20240828, skip this date
Already processed for date 20240827, skip this date
Already processed for date 20240826, skip this date
Already processed for date 20240823, skip this date
Already processed for date 20240822, skip this date
Already processed for date 20240821, skip this date
Already processed for date 20240820, skip this date
Already processed for date 20240819, skip this date
Already processed for date 20240816, skip this date
Already processed for date 20240815, skip this date
Already processed for date 20240814, skip this date
Already processed for date 20240813, skip this date
Already processed for date 20240812, skip this date
Already processed for date 20240809, skip this date
Already processed for date 20240808, skip this date
Already processed for date 20240807, skip this date
Already processed for date 20240806, skip this date
Already processed for date 20240805, skip this date
Already processed for date 20240802, skip this date
Already processed for date 20240801, skip this date
Already processed for date 20240731, skip this date
Already processed for date 20240730, skip this date
Already processed for date 20240729, skip this date
Already processed for date 20240726, skip this date
Already processed for date 20240725, skip this date
Already processed for date 20240724, skip this date
Already processed for date 20240723, skip this date
Already processed for date 20240722, skip this date
Already processed for date 20240719, skip this date
Already processed for date 20240718, skip this date
Already processed for date 20240717, skip this date
Already processed for date 20240716, skip this date
Already processed for date 20240715, skip this date
Already processed for date 20240712, skip this date
Already processed for date 20240711, skip this date
Already processed for date 20240710, skip this date
Already processed for date 20240709, skip this date
Already processed for date 20240708, skip this date
Already processed for date 20240705, skip this date
Already processed for date 20240703, skip this date
Already processed for date 20240702, skip this date
Already processed for date 20240701, skip this date
Already processed for date 20240628, skip this date
Already processed for date 20240627, skip this date
Already processed for date 20240626, skip this date
Already processed for date 20240625, skip this date
Already processed for date 20240624, skip this date
Already processed for date 20240621, skip this date
Already processed for date 20240620, skip this date
Already processed for date 20240618, skip this date
Already processed for date 20240617, skip this date
Already processed for date 20240614, skip this date
Already processed for date 20240613, skip this date
Already processed for date 20240612, skip this date
Already processed for date 20240611, skip this date
Already processed for date 20240610, skip this date
Already processed for date 20240607, skip this date
Already processed for date 20240606, skip this date
Already processed for date 20240605, skip this date
Already processed for date 20240604, skip this date
Already processed for date 20240603, skip this date
Already processed for date 20240531, skip this date
Already processed for date 20240530, skip this date
Already processed for date 20240529, skip this date
Already processed for date 20240528, skip this date
Already processed for date 20240524, skip this date
Already processed for date 20240523, skip this date
Already processed for date 20240522, skip this date
Already processed for date 20240521, skip this date
Already processed for date 20240520, skip this date
Already processed for date 20240517, skip this date
Already processed for date 20240516, skip this date
Already processed for date 20240515, skip this date
Already processed for date 20240514, skip this date
Already processed for date 20240513, skip this date
Already processed for date 20240510, skip this date
Already processed for date 20240509, skip this date
Already processed for date 20240508, skip this date
Already processed for date 20240507, skip this date
Already processed for date 20240506, skip this date
Already processed for date 20240503, skip this date
Already processed for date 20240502, skip this date
Already processed for date 20240501, skip this date
Already processed for date 20240430, skip this date
Already processed for date 20240429, skip this date
Already processed for date 20240426, skip this date
Already processed for date 20240425, skip this date
Already processed for date 20240424, skip this date
Already processed for date 20240423, skip this date
Already processed for date 20240422, skip this date
Already processed for date 20240419, skip this date
Already processed for date 20240418, skip this date
Already processed for date 20240417, skip this date
Already processed for date 20240416, skip this date
Already processed for date 20240415, skip this date
Already processed for date 20240412, skip this date
Already processed for date 20240411, skip this date
Already processed for date 20240410, skip this date
Already processed for date 20240409, skip this date
Already processed for date 20240408, skip this date
Already processed for date 20240405, skip this date
Already processed for date 20240404, skip this date
Already processed for date 20240403, skip this date
Already processed for date 20240402, skip this date
Already processed for date 20240401, skip this date
Already processed for date 20240328, skip this date
Already processed for date 20240327, skip this date
Already processed for date 20240326, skip this date
Already processed for date 20240325, skip this date
Already processed for date 20240322, skip this date
Already processed for date 20240321, skip this date
Already processed for date 20240320, skip this date
Already processed for date 20240319, skip this date
Already processed for date 20240318, skip this date
Already processed for date 20240315, skip this date
Already processed for date 20240314, skip this date
Already processed for date 20240313, skip this date
Already processed for date 20240312, skip this date
Already processed for date 20240311, skip this date
Already processed for date 20240308, skip this date
Already processed for date 20240307, skip this date
Already processed for date 20240306, skip this date
Already processed for date 20240305, skip this date
Already processed for date 20240304, skip this date
Already processed for date 20240301, skip this date
Already processed for date 20240229, skip this date
Already processed for date 20240228, skip this date
Already processed for date 20240227, skip this date
Already processed for date 20240226, skip this date
Already processed for date 20240223, skip this date
Already processed for date 20240222, skip this date
Already processed for date 20240221, skip this date
Already processed for date 20240220, skip this date
Already processed for date 20240216, skip this date
Already processed for date 20240215, skip this date
Already processed for date 20240214, skip this date
Already processed for date 20240213, skip this date
Already processed for date 20240212, skip this date
Already processed for date 20240209, skip this date
Already processed for date 20240208, skip this date
Already processed for date 20240207, skip this date
Already processed for date 20240206, skip this date
Already processed for date 20240205, skip this date
Already processed for date 20240202, skip this date
Already processed for date 20240201, skip this date
Already processed for date 20240131, skip this date
Already processed for date 20240130, skip this date
Already processed for date 20240129, skip this date
Already processed for date 20240126, skip this date
Already processed for date 20240125, skip this date
Already processed for date 20240124, skip this date
Already processed for date 20240123, skip this date
Already processed for date 20240122, skip this date
Already processed for date 20240119, skip this date
Already processed for date 20240118, skip this date
Already processed for date 20240117, skip this date
Already processed for date 20240116, skip this date
Already processed for date 20240112, skip this date
Already processed for date 20240111, skip this date
Already processed for date 20240110, skip this date
Already processed for date 20240109, skip this date
Already processed for date 20240108, skip this date
Already processed for date 20240105, skip this date
Already processed for date 20240104, skip this date
Already processed for date 20240103, skip this date
Already processed for date 20240102, skip this date
Already processed for date 20231229, skip this date
Already processed for date 20231228, skip this date
Already processed for date 20231227, skip this date
Already processed for date 20231226, skip this date
Already processed for date 20231222, skip this date
Already processed for date 20231221, skip this date
Already processed for date 20231220, skip this date
Already processed for date 20231219, skip this date
Already processed for date 20231218, skip this date
Already processed for date 20231215, skip this date
Already processed for date 20231214, skip this date
Already processed for date 20231213, skip this date
Already processed for date 20231212, skip this date
Already processed for date 20231211, skip this date
Already processed for date 20231208, skip this date
Already processed for date 20231207, skip this date
Already processed for date 20231206, skip this date
Already processed for date 20231205, skip this date
Already processed for date 20231204, skip this date
Already processed for date 20231201, skip this date
Already processed for date 20231130, skip this date
Already processed for date 20231129, skip this date
Already processed for date 20231128, skip this date
Already processed for date 20231127, skip this date
Already processed for date 20231124, skip this date
Already processed for date 20231122, skip this date
Already processed for date 20231121, skip this date
Already processed for date 20231120, skip this date
Already processed for date 20231117, skip this date
Already processed for date 20231116, skip this date
Already processed for date 20231115, skip this date
Already processed for date 20231114, skip this date
Already processed for date 20231113, skip this date
Already processed for date 20231110, skip this date
Already processed for date 20231109, skip this date
Already processed for date 20231108, skip this date
Already processed for date 20231107, skip this date
Already processed for date 20231106, skip this date
Already processed for date 20231103, skip this date
Already processed for date 20231102, skip this date
Already processed for date 20231101, skip this date
Already processed for date 20231031, skip this date
Already processed for date 20231030, skip this date
Already processed for date 20231027, skip this date
Already processed for date 20231026, skip this date
Already processed for date 20231025, skip this date
Already processed for date 20231024, skip this date
Already processed for date 20231023, skip this date
Already processed for date 20231020, skip this date
Already processed for date 20231019, skip this date
Already processed for date 20231018, skip this date
Already processed for date 20231017, skip this date
Already processed for date 20231016, skip this date
Already processed for date 20231013, skip this date
Already processed for date 20231012, skip this date
Already processed for date 20231011, skip this date
Already processed for date 20231010, skip this date
Already processed for date 20231009, skip this date
Already processed for date 20231006, skip this date
Already processed for date 20231005, skip this date
Already processed for date 20231004, skip this date
Already processed for date 20231003, skip this date
Already processed for date 20231002, skip this date

# GA 設定

In [26]:
import json
import random
from datetime import datetime
from datetime import timedelta

def split_expand(env, path_expand):
    # 解析日期
    start_day = datetime.strptime(env['start_date'], '%Y%m%d')
    end_day = datetime.strptime(env['end_date'], '%Y%m%d')

    # read train data
    with open(path_expand, 'r') as f:
        content = f.read().strip()
        data_points = json.loads(content)

    # split to training and testing
    total_days = (end_day - start_day).days + 1
    split_point = int(total_days * 3 / 4)
    training_end_day = start_day + timedelta(days=split_point - 1)
    testing_start_day = training_end_day + timedelta(days=1)
    train_datarange = {}
    for date_str, value in data_points["output_data"].items():
        date = datetime.strptime(date_str, '%Y%m%d')
        if start_day <= date <= training_end_day:
            train_datarange[date_str] = value
    test_datarange = {}
    for date_str, value in data_points["output_data"].items():
        date = datetime.strptime(date_str, '%Y%m%d')
        if testing_start_day <= date <= end_day:
            test_datarange[date_str] = value



    return train_datarange, test_datarange

In [27]:
train_datarange, test_datarange = split_expand(env, path_expand)
print(len(train_datarange))
print(train_datarange.keys())
print(len(test_datarange))
print(test_datarange.keys())

187
dict_keys(['20240628', '20240627', '20240626', '20240625', '20240624', '20240621', '20240620', '20240618', '20240617', '20240614', '20240613', '20240612', '20240611', '20240610', '20240607', '20240606', '20240605', '20240604', '20240603', '20240531', '20240530', '20240529', '20240528', '20240524', '20240523', '20240522', '20240521', '20240520', '20240517', '20240516', '20240515', '20240514', '20240513', '20240510', '20240509', '20240508', '20240507', '20240506', '20240503', '20240502', '20240501', '20240430', '20240429', '20240426', '20240425', '20240424', '20240423', '20240422', '20240419', '20240418', '20240417', '20240416', '20240415', '20240412', '20240411', '20240410', '20240409', '20240408', '20240405', '20240404', '20240403', '20240402', '20240401', '20240328', '20240327', '20240326', '20240325', '20240322', '20240321', '20240320', '20240319', '20240318', '20240315', '20240314', '20240313', '20240312', '20240311', '20240308', '20240307', '20240306', '20240305', '20240304', '20240301', '20240229', '20240228', '20240227', '20240226', '20240223', '20240222', '20240221', '20240220', '20240216', '20240215', '20240214', '20240213', '20240212', '20240209', '20240208', '20240207', '20240206', '20240205', '20240202', '20240201', '20240131', '20240130', '20240129', '20240126', '20240125', '20240124', '20240123', '20240122', '20240119', '20240118', '20240117', '20240116', '20240112', '20240111', '20240110', '20240109', '20240108', '20240105', '20240104', '20240103', '20240102', '20231229', '20231228', '20231227', '20231226', '20231222', '20231221', '20231220', '20231219', '20231218', '20231215', '20231214', '20231213', '20231212', '20231211', '20231208', '20231207', '20231206', '20231205', '20231204', '20231201', '20231130', '20231129', '20231128', '20231127', '20231124', '20231122', '20231121', '20231120', '20231117', '20231116', '20231115', '20231114', '20231113', '20231110', '20231109', '20231108', '20231107', '20231106', '20231103', '20231102', '20231101', '20231031', '20231030', '20231027', '20231026', '20231025', '20231024', '20231023', '20231020', '20231019', '20231018', '20231017', '20231016', '20231013', '20231012', '20231011', '20231010', '20231009', '20231006', '20231005', '20231004', '20231003', '20231002'])
64
dict_keys(['20240930', '20240927', '20240926', '20240925', '20240924', '20240923', '20240920', '20240919', '20240918', '20240917', '20240916', '20240913', '20240912', '20240911', '20240910', '20240909', '20240906', '20240905', '20240904', '20240903', '20240830', '20240829', '20240828', '20240827', '20240826', '20240823', '20240822', '20240821', '20240820', '20240819', '20240816', '20240815', '20240814', '20240813', '20240812', '20240809', '20240808', '20240807', '20240806', '20240805', '20240802', '20240801', '20240731', '20240730', '20240729', '20240726', '20240725', '20240724', '20240723', '20240722', '20240719', '20240718', '20240717', '20240716', '20240715', '20240712', '20240711', '20240710', '20240709', '20240708', '20240705', '20240703', '20240702', '20240701'])

# GA Training and Testing

Accuracy

In [28]:
from api import genetic_algorithm
from api import eval

# setting --------------------------------
mode = 0     # 0: 準確率, 1: 期望值
# ----------------------------------------

path_str = "exp"
if mode == 0:
    path_str = path_str + "_ac"
else:
    path_str = path_str + "_ev"

out_folder = f"{env['path_out']}/{env['stock_id']}/{env['start_date']}_{env['end_date']}" + f"{path_str}"
state_file= out_folder + '/state.json'
file_gen= out_folder + '/generation_results.json'
file_result= out_folder + '/result.json'


print("Start, 第一次跑的話請確認state是空的")
best_individual = genetic_algorithm(factors, population_size=20, generations=50, state_file=state_file, results_file=file_gen, env=env, mode=mode, datarange=train_datarange)
print(f"Best individual: {best_individual}")

individual = best_individual
res_train = eval(individual, env['stock_id'], train_datarange, env)
res_test = eval(individual, env['stock_id'], test_datarange, env)
res = {
    "train": res_train,
    "test": res_test,
    "individual": individual,
}
print(res)
print(file_result)
with open(file_result, 'w') as f:
    json.dump(res, f, ensure_ascii=False, indent=4)

Start, 第一次跑的話請確認state是空的
Best individual: [0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0]
{'train': {'tp': 17, 'fp': 13, 'tn': 83, 'fn': 74, 'avail_count': 187, 'ttl_count': 187, 'accuracy': 0.5347593582887701, 'precision': 0.5666666666666667, 'recall': 0.18681318681318682, 'ev': 0.0010359104036120198, 'precision_ev': 0.0030375634098591744}, 'test': {'tp': 13, 'fp': 4, 'tn': 24, 'fn': 23, 'avail_count': 64, 'ttl_count': 64, 'accuracy': 0.578125, 'precision': 0.7647058823529411, 'recall': 0.3611111111111111, 'ev': 0.002605639790637255, 'precision_ev': 0.009800562033183965}, 'individual': [0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0]}
out_stock/GA_sot_4omini//TSLA/20231001_20240930exp_ac/result.json

In [29]:
df = pd.DataFrame([res['train'], res['test']], index=['train', 'test'])
df

,tp,fp,tn,fn,avail_count,ttl_count,accuracy,precision,recall,ev,precision_ev
train,17,13,83,74,187,187,0.534759,0.566667,0.186813,0.001036,0.003038
test,13,4,24,23,64,64,0.578125,0.764706,0.361111,0.002606,0.009801

Expected Value

In [30]:
from api import genetic_algorithm
from api import eval

# setting --------------------------------
mode = 1     # 0: 準確率, 1: 期望值
# ----------------------------------------

path_str = "exp"
if mode == 0:
    path_str = path_str + "_ac"
else:
    path_str = path_str + "_ev"

out_folder = f"{env['path_out']}/{env['stock_id']}/{env['start_date']}_{env['end_date']}" + f"{path_str}"
state_file= out_folder + '/state.json'
file_gen= out_folder + '/generation_results.json'
file_result= out_folder + '/result.json'


print("Start, 第一次跑的話請確認state是空的")
best_individual = genetic_algorithm(factors, population_size=20, generations=50, state_file=state_file, results_file=file_gen, env=env, mode=mode, datarange=train_datarange)
print(f"Best individual: {best_individual}")

individual = best_individual
res_train = eval(individual, env['stock_id'], train_datarange, env)
res_test = eval(individual, env['stock_id'], test_datarange, env)
res = {
    "train": res_train,
    "test": res_test,
    "individual": individual,
}
print(res)
print(file_result)
with open(file_result, 'w') as f:
    json.dump(res, f, ensure_ascii=False, indent=4)

Start, 第一次跑的話請確認state是空的
Best individual: [1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1]
{'train': {'tp': 18, 'fp': 15, 'tn': 80, 'fn': 73, 'avail_count': 186, 'ttl_count': 187, 'accuracy': 0.5268817204301075, 'precision': 0.5454545454545454, 'recall': 0.1978021978021978, 'ev': 0.0009772737570117058, 'precision_ev': 0.0026552355837656354}, 'test': {'tp': 13, 'fp': 4, 'tn': 24, 'fn': 23, 'avail_count': 64, 'ttl_count': 64, 'accuracy': 0.578125, 'precision': 0.7647058823529411, 'recall': 0.3611111111111111, 'ev': 0.002605639790637255, 'precision_ev': 0.009800562033183965}, 'individual': [1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1]}
out_stock/GA_sot_4omini//TSLA/20231001_20240930exp_ev/result.json

In [31]:
df = pd.DataFrame([res['train'], res['test']], index=['train', 'test'])
df

,tp,fp,tn,fn,avail_count,ttl_count,accuracy,precision,recall,ev,precision_ev
train,18,15,80,73,186,187,0.526882,0.545455,0.197802,0.000977,0.002655
test,13,4,24,23,64,64,0.578125,0.764706,0.361111,0.002606,0.009801

# show old data

In [32]:
import os
import json
import pandas as pd
from api import eval

folders = os.listdir(env['path_out'])
results = []
index = []

for folder in folders:
    if folder == "factors_eng.json" or folder == "factors.json" or folder == "old_expand":
        continue
    folders_result = os.listdir(f"{env['path_out']}{folder}")
    # print(f"{folder}:")
    for file in folders_result:
        if file == "factors.json" or file == "factors1.json" or file == "factors2.json" or file == "expand.json" or file == "expand1.json" or file == "expand2.json":
            continue
        path = f"{env['path_out']}{folder}/{file}/result.json"
        with open(path, 'r') as f:
            json_data = json.load(f)
        # print(json_data)
        results.append(json_data['test'])
        index.append(f"{folder}_{file}")
        

print(f"共有 {len(results), len(index)} 筆資料")
print(results)

df = pd.DataFrame(results, index=index)
selected_columns = ['accuracy', 'precision', 'ev', 'precision_ev']  # 替換為您需要的欄位名稱
df_selected = df.loc[:, selected_columns]
df_sorted = df_selected.sort_index()
df_sorted

共有 (16, 16) 筆資料
[{'tp': 19, 'fp': 18, 'tn': 4, 'fn': 6, 'avail_count': 47, 'ttl_count': 47, 'accuracy': 0.48936170212765956, 'precision': 0.5135135135135135, 'recall': 0.76, 'ev': 1.8130582968558726e-06, 'precision_ev': 0.000490741739743881}, {'tp': 19, 'fp': 18, 'tn': 4, 'fn': 6, 'avail_count': 47, 'ttl_count': 47, 'accuracy': 0.48936170212765956, 'precision': 0.5135135135135135, 'recall': 0.76, 'ev': 1.8130582968558726e-06, 'precision_ev': 0.000490741739743881}, {'tp': 17, 'fp': 28, 'tn': 9, 'fn': 9, 'avail_count': 63, 'ttl_count': 64, 'accuracy': 0.4126984126984127, 'precision': 0.37777777777777777, 'recall': 0.6538461538461539, 'ev': -0.0010705071865823052, 'precision_ev': -0.0019024197245643294}, {'tp': 17, 'fp': 25, 'tn': 11, 'fn': 10, 'avail_count': 63, 'ttl_count': 64, 'accuracy': 0.4444444444444444, 'precision': 0.40476190476190477, 'recall': 0.6296296296296297, 'ev': -0.001617349351489699, 'precision_ev': -0.0024345897540011333}, {'tp': 24, 'fp': 15, 'tn': 11, 'fn': 14, 'avail_count': 64, 'ttl_count': 64, 'accuracy': 0.546875, 'precision': 0.6153846153846154, 'recall': 0.631578947368421, 'ev': -0.0007766285851911669, 'precision_ev': 0.0006947447611317372}, {'tp': 24, 'fp': 15, 'tn': 11, 'fn': 14, 'avail_count': 64, 'ttl_count': 64, 'accuracy': 0.546875, 'precision': 0.6153846153846154, 'recall': 0.631578947368421, 'ev': -0.0007766285851911669, 'precision_ev': 0.0006947447611317372}, {'tp': 10, 'fp': 15, 'tn': 9, 'fn': 8, 'avail_count': 42, 'ttl_count': 63, 'accuracy': 0.4523809523809524, 'precision': 0.4, 'recall': 0.5555555555555556, 'ev': 0.0027789412114150747, 'precision_ev': 0.0017356763077262275}, {'tp': 22, 'fp': 21, 'tn': 7, 'fn': 3, 'avail_count': 53, 'ttl_count': 63, 'accuracy': 0.5471698113207547, 'precision': 0.5116279069767442, 'recall': 0.88, 'ev': 0.0039955090355731715, 'precision_ev': 0.002774070128485443}, {'tp': 13, 'fp': 4, 'tn': 24, 'fn': 23, 'avail_count': 64, 'ttl_count': 64, 'accuracy': 0.578125, 'precision': 0.7647058823529411, 'recall': 0.3611111111111111, 'ev': 0.002605639790637255, 'precision_ev': 0.009800562033183965}, {'tp': 13, 'fp': 4, 'tn': 24, 'fn': 23, 'avail_count': 64, 'ttl_count': 64, 'accuracy': 0.578125, 'precision': 0.7647058823529411, 'recall': 0.3611111111111111, 'ev': 0.002605639790637255, 'precision_ev': 0.009800562033183965}, {'tp': 14, 'fp': 14, 'tn': 19, 'fn': 17, 'avail_count': 64, 'ttl_count': 64, 'accuracy': 0.515625, 'precision': 0.5, 'recall': 0.45161290322580644, 'ev': 3.6534596626772685e-05, 'precision_ev': -0.0024710806223452926}, {'tp': 13, 'fp': 13, 'tn': 19, 'fn': 18, 'avail_count': 63, 'ttl_count': 64, 'accuracy': 0.5079365079365079, 'precision': 0.5, 'recall': 0.41935483870967744, 'ev': 8.871203198191398e-05, 'precision_ev': -0.002306123692662687}, {'tp': 12, 'fp': 18, 'tn': 13, 'fn': 9, 'avail_count': 52, 'ttl_count': 63, 'accuracy': 0.4807692307692308, 'precision': 0.4, 'recall': 0.5714285714285714, 'ev': 0.003241445965336082, 'precision_ev': 0.003395522186534266}, {'tp': 12, 'fp': 14, 'tn': 17, 'fn': 9, 'avail_count': 52, 'ttl_count': 63, 'accuracy': 0.5576923076923077, 'precision': 0.46153846153846156, 'recall': 0.5714285714285714, 'ev': 0.00468352048239375, 'precision_ev': 0.005279056349492509}, {'tp': 20, 'fp': 21, 'tn': 12, 'fn': 11, 'avail_count': 64, 'ttl_count': 64, 'accuracy': 0.5, 'precision': 0.4878048780487805, 'recall': 0.6451612903225806, 'ev': 0.000724271330215233, 'precision_ev': -0.000584262413968206}, {'tp': 22, 'fp': 22, 'tn': 11, 'fn': 8, 'avail_count': 63, 'ttl_count': 64, 'accuracy': 0.5238095238095238, 'precision': 0.5, 'recall': 0.7333333333333333, 'ev': 0.0005010909647635902, 'precision_ev': -0.0008870475875880886}]

                               accuracy  precision        ev  precision_ev
2330_20231001_20240930exp_ac   0.452381   0.400000  0.002779      0.001736
2330_20231001_20240930exp_ev   0.547170   0.511628  0.003996      0.002774
2454_20231001_20240930exp_ac   0.480769   0.400000  0.003241      0.003396
2454_20231001_20240930exp_ev   0.557692   0.461538  0.004684      0.005279
AAPL_20231001_20240930exp_ac   0.546875   0.615385 -0.000777      0.000695
AAPL_20231001_20240930exp_ev   0.546875   0.615385 -0.000777      0.000695
AMZN_20231001_20240630exp_ac   0.489362   0.513514  0.000002      0.000491
AMZN_20231001_20240630exp_ev   0.489362   0.513514  0.000002      0.000491
AMZN_20231001_20240930exp_ac   0.412698   0.377778 -0.001071     -0.001902
AMZN_20231001_20240930exp_ev   0.444444   0.404762 -0.001617     -0.002435
GOOGL_20231001_20240930exp_ac  0.515625   0.500000  0.000037     -0.002471
GOOGL_20231001_20240930exp_ev  0.507937   0.500000  0.000089     -0.002306
MSFT_20231001_20240930exp_ac   0.500000   0.487805  0.000724     -0.000584
MSFT_20231001_20240930exp_ev   0.523810   0.500000  0.000501     -0.000887
TSLA_20231001_20240930exp_ac   0.578125   0.764706  0.002606      0.009801
TSLA_20231001_20240930exp_ev   0.578125   0.764706  0.002606      0.009801

In [33]:
# import os
# import json
# import pandas as pd
# from api import eval

# folders = os.listdir(env['path_out'])
# results = []
# index = []
# print(env['start_date'], env['end_date'])

# for folder in folders:
#     if folder == "factors_eng.json" or folder == "factors.json" or folder == "old_expand":
#         continue
#     folders_result = os.listdir(f"{env['path_out']}{folder}")
#     print(f"{folder}:")
#     for file in folders_result:
#         if file == "factors.json" or file == "expand.json" or file == "expand1.json" or file == "expand2.json":
#             continue
#         path = f"{env['path_out']}{folder}/{file}/generation_results.json"
#         with open(path, 'r') as f:
#             content = f.read().strip()
#         # print(file)
#         best_individual = []
#         for text in content.split('\n'):
#             data = json.loads(text)
#             best_individual = data['best_individual']

#         try:
#             individual = best_individual
#             print(f"{env['path_out']}{folder}/expand.json")
#             train_datarange, test_datarange = split_expand(env, f"{env['path_out']}{folder}/expand.json")
#             res_train = eval(individual, env['stock_id'], train_datarange)
#             res_test = eval(individual, env['stock_id'], test_datarange)
#             res = {
#                 "train": res_train,
#                 "test": res_test,
#                 "individual": individual,
#             }

#             file_result = f"{env['path_out']}{folder}/{file}/result.json"
#             print(file_result)
#             with open(file_result, 'w') as f:
#                 json.dump(res, f, ensure_ascii=False, indent=4)
#         except:
#             print("\tError")
#             pass